# Generated by Django 5.2.2 on 2025-08-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queuejob',
            fields=[
                ('id', models.AutoField(help_text='Database primary key', primary_key=True, serialize=False)),
                ('queuejob_id', models.CharField(help_text='Business unique queuejob identifier', max_length=50, unique=True)),
                ('queuejob_name', models.CharField(blank=True, default='Untitled Queuejob', help_text='Human readable queuejob name', max_length=100)),
                ('queuejob_hash', models.CharField(blank=True, help_text="Hash of the queuejob command,files,etc. regrad as the same job's resubmit if the hash is the same.", max_length=100)),
                ('user_id', models.CharField(blank=True, help_text='User identifier django_myusername123; supabase_otherusername456; etc.', max_length=200)),
                ('user_email', models.EmailField(blank=True, help_text='User email for notifications', max_length=254)),
                ('modal_function_call_id', models.CharField(blank=True, help_text='Modal function call ID', max_length=100)),
                ('modal_app_name', models.CharField(blank=True, help_text='Modal app name', max_length=100)),
                ('modal_function_name', models.CharField(blank=True, help_text='Modal function name', max_length=100)),
                ('command', models.TextField(blank=True, help_text='Command or parameters to execute')),
                ('environment_vars', models.JSONField(blank=True, default=dict, help_text='Environment variables as JSON')),
                ('status_history', models.JSONField(blank=True, default=list, help_text='Status change history as JSON array')),
                ('current_status', models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('CLEANED', 'Cleaned'), ('TIMEOUT', 'Timeout')], default='SUBMITTED', help_text='Current queuejob status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Queuejob creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'current_status'], name='deepmd_moda_user_id_71d81c_idx'), models.Index(fields=['current_status', '-created_at'], name='deepmd_moda_current_bf4264_idx'), models.Index(fields=['modal_app_name', 'modal_function_name'], name='deepmd_moda_modal_a_9a927e_idx')],
            },
        ),
    ]
