# Generated by Django 5.2.2 on 2025-08-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepmd_modal_batch_queue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuejob',
            name='modal_volume_name',
            field=models.CharField(blank=True, help_text='Modal volume name', max_length=100),
        ),
    ]
